project: 
  type: website
  output-dir: docs

website: 
  title: "Projektowanie aplikacji internetowych i korporacyjnych"
  description: "Kurs dla studentów WAT w Warszawie"
  site-url: https://sebkaz-teaching.github.io/paikw
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section : "Wykłady"
        contents:
        - href: lectures/wyklad1.qmd
        - href: lectures/wyklad2.qmd
        - href: lectures/wyklad3.qmd
        - href: lectures/wyklad4.qmd
        - href: lectures/wyklad5.qmd
      - section : "Laboratoria"
        contents:
        - href: labs/lab1.qmd
        - href: labs/lab2.qmd
        - href: labs/lab3.qmd
        - href: labs/lab4.qmd
        - href: labs/lab5.qmd
       
  navbar:
    left: 
          - href: indexS.qmd
            text: 222890-S
          - href: ksiazki.qmd
            text: Książki
          
  page-footer: "Copyright 2026, Sebastian Zając"
format:
  html:
    page-layout: article
    theme: minty
    css: style.css
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    self-contained-math: true
    code-overflow: wrap
    code-block-background: true
    link-external-newwindow: true