---
title: Książki i strony WWW
---

## Książki 

### Stream Processing

1. G. Maas, F. Garillot _Stream Processing with Apache Spark_ [Zobacz opis](http://helion.pl/view/111546/e_11pp.html) lub [Kup e-book](http://helion.pl/add111546~e_11pp_ebook)

2. F. Hueske, V. Kalavri _Stream Processing with Apache Flink_ [Zobacz opis](http://helion.pl/view/111546/e_13f8.html) lub [Kup e-book](http://helion.pl/add111546~e_13f8_ebook)

<div id="bellemare">
3. A. Bellemare _Mikrousługi oparte na zdarzeniach. Wykorzystanie danych w organizacji na dużą skalę_ [Zobacz opis](http://helion.pl/view/111546/miopzd) lub [Kup](http://helion.pl/add111546~miopzd)
</div>

### Machine Learning with Pyton

1. W. McKinney _Python w analizie danych. Przetwarzanie danych za pomocą pakietów Pandas i NumPy oraz środowiska IPython. Wydanie II_  [Zobacz opis](http://helion.pl/view/111546/pytand.html) lub [Kup książkę](http://helion.pl/add111546~pytand), [Kup e-book](http://helion.pl/add111546~pytand_ebook)

2. D. McIlwraith, H. Marmanis, D. Babenko _Inteligentna sieć. Algorytmy przyszłości. Wydanie II (ebook)_ [Zobacz opis](http://helion.pl/view/111546/intsi2.html) lub [Kup książkę](http://helion.pl/add111546~intsi2), [Kup e-book](http://helion.pl/add111546~intsi2_ebook)

3. Joel Grus _Data science od podstaw. Analiza danych w Pythonie. Wydanie II_. [Zobacz opis](http://helion.pl/view/111546/dascp2.html) lub [Kup książkę](http://helion.pl/add111546~dascp2), [Kup e-book](http://helion.pl/add111546~dascp2_ebook).

4. John W. Foreman _Mistrz analizy danych. Od danych do wiedzy_. [Zobacz opis](http://helion.pl/view/111546/mianda.html) lub [Kup książkę](http://helion.pl/add111546~mianda), [Kup e-book](http://helion.pl/add111546~mianda_ebook).

5. A. Geron _Uczenie maszynowe z użyciem Scikit-Learn i TensorFlow. Wydanie II_. [Zobacz opis](http://helion.pl/view/111546/uczem2.html) lub [Kup książkę](http://helion.pl/add111546~uczem2), [Kup e-book](http://helion.pl/add111546~uczem2_ebook).

6. Alberto Boschetti, Luca Massaron _Python. Podstawy nauki o danych_. [Zobacz opis](http://helion.pl/view/111546/pypod2.html) lub [Kup książkę](http://helion.pl/add111546~pypod2).

7. Sebastian Raschka _Python. Uczenie maszynowe. Wydanie II_. [Zobacz opis](http://helion.pl/view/111546/pythu2.html) lub [Kup książkę](http://helion.pl/add111546~pythu2).

8. R. Schutt, C. O'Neil _Badanie danych. Raport z pierwszej lini działań_. [Zobacz opis](http://helion.pl/view/111546/badada.html) lub [Kup książkę](http://helion.pl/add111546~badada).

9. T. Segaran _Nowe usługi 2.0. Przewodnik po analizie zbiorów danych_
[Zobacz opis](http://helion.pl/view/111546/noweus.html) lub [Kup książkę](http://helion.pl/add111546~noweus), [Kup e-book](http://helion.pl/add111546~noweus_ebook)

### Deep Learning

1. F. Chollet _Deep Learning. Praca z językiem Python i biblioteką Keras._ [Zobacz opis](http://helion.pl/view/111546/delepy.html) lub [Kup książkę](http://helion.pl/add111546~delepy), [Kup e-book](http://helion.pl/add111546~delepy_ebook)

2. J. Patterson, A. Gibson _Deep Learning. Praktyczne wprowadzenie (ebook)_ [Zobacz opis](http://helion.pl/view/111546/deeple.html) lub [Kup e-book](http://helion.pl/add111546~deeple_ebook)

3. V. Zocca, G. Spacagna, D. Slater, P. Roelants. _Deep Learning. Uczenie głębokie z językiem Python. Sztuczna inteligencja i sieci neuronowe_ [Zobacz opis](http://helion.pl/view/111546/deelea.html) lub [Kup ebook](http://helion.pl/add111546~deelea_ebook)

4. D. Osinga _Deep Learning. Receptury_ [Zobacz opis](http://helion.pl/view/111546/delere.html) lub [Kup książkę](http://helion.pl/add111546~delere), [Kup e-book](http://helion.pl/add111546~delere_ebook)

5. S. Weidman _Uczenie głębokie od zera. Podstawy implementacji w Pythonie_ [Zobacz opis](http://helion.pl/view/111546/uczgle.html) lub [Kup książkę](http://helion.pl/add111546~uczgle), [Kup e-book](http://helion.pl/add111546~uczgle_ebook)

6. D. Foster _Deep learning i modelowanie generatywne. Jak nauczyć komputer malowania, pisania, komponowania i grania_ [Zobacz opis](http://helion.pl/view/111546/deelmg.html) lub [Kup książkę](http://helion.pl/add111546~deelmg), [Kup e-book](http://helion.pl/add111546~deelmg_ebook)

7. J. Howard, S. Gugger _Deep learning dla programistów. Budowanie aplikacji AI za pomocą fastai i PyTorch_ [Zobacz opis](http://helion.pl/view/111546/delepr.html) lub [Kup książkę](http://helion.pl/add111546~delepr), [Kup e-book](http://helion.pl/add111546~delepr_ebook)


### Apache SPARK

1. J. S. Damji, B. Wenig, T. Das, D. Lee _Spark. Błyskawiczna analiza danych_ [Zobacz opis](http://helion.pl/view/111546/sparb2.html) lub [Kup](http://helion.pl/add111546~sparb2)

1. _Spark. Zaawansowana analiza danych (ebook)_ [Zobacz opis](http://helion.pl/view/111546/sparkz.html) lub [Kup e-book](http://helion.pl/add111546~sparkz_ebook)

2. B. Chambers, M. Zaharia _Spark: The Definitive Guide. Big Data Processing Made Simple (ebook)_ [Zobacz opis](http://helion.pl/view/111546/e_0qdv.html) lub [Kup e-book](http://helion.pl/add111546~e_0qdv_ebook)

3. J. Quddus _Machine Learning with Apache Spark Quick Start Guide (ebook)_ [Zobacz opis](http://helion.pl/view/111546/e_15el.html) lub [Kup e-book](http://helion.pl/add111546~e_15el._ebook)


### Programowanie

1. G. Coldwind _Zrozumieć programowanie_ [Zobacz opis](http://helion.pl/view/111546/e_1ott.html) lub [Kup książkę](http://helion.pl/add111546~e_1ott), [Kup e-book](http://helion.pl/add111546~e_1ott_ebook)

2. A. Allain _C++. Przewodnik dla początkujących_ [Zobacz opis](http://helion.pl/view/111546/cppppo.html) lub [Kup książkę](http://helion.pl/add111546~cppppo), [Kup e-book](http://helion.pl/add111546~cppppo_ebook)

3. S. Dasgupta, C. Papadimitriou, U. Vazirani _Algorytmy_ PWN.

### Docker

1. J. Krochmalski _Docker. Projektowanie i wdrażanie aplikacji_ [Zobacz opis](http://helion.pl/view/111546/docpro.html) lub [Kup książkę](http://helion.pl/add111546~docpro), [Kup e-book](http://helion.pl/add111546~docpro_ebook)

2. R. McKendrick, S. Gallagher _Docker. Programowanie aplikacji dla zaawansowanych. Wydanie II_ [Zobacz opis](http://helion.pl/view/111546/dockaz.html) lub [Kup książkę](http://helion.pl/add111546~dockaz), [Kup e-book](http://helion.pl/add111546~dockaz_ebook)

### Github

1. P. Bell, B. Beer _GitHub. Przyjazny przewodnik (ebook)_ [Zobacz opis](http://helion.pl/view/111546/github.html) lub [Kup e-book](http://helion.pl/add111546~github_ebook)


### Python

1. C. Althoff, _Programista Samouk. Profesjonalny przewodnik do samodzielnej nauki kodowania._ [Zobacz opis](http://helion.pl/view/111546/proprs) lub [Kup teraz](http://helion.pl/add111546~proprs), [Kup e-book](http://helion.pl/add111546~proprs_ebook)

2. A. Sweigart, _Automatyzacja nudnych zadań z pythonem_. [Zobacz opis](http://helion.pl/view/111546/autopy) lub [Kup książkę](http://helion.pl/add111546~autopy), [Kup e-book](http://helion.pl/add111546~autopy_ebook)

3. K. Reitz, T. Schlusser _Przewodnik po Pythonie. Dobre praktyki i praktyczne narzędzia_. [Zobacz opis](http://helion.pl/view/111546/przepy) lub [Kup teraz](http://helion.pl/add111546~przepy), [Kup e-book](http://helion.pl/add111546~przepy_ebook)

### Różne

1. B.Tate, L. Carslon, C. Hiibs, _Ruby on Rails. Wprowadzenie. Wydanie II_ [Zobacz opis](http://helion.pl/view/111546/rubyw2) lub [Kup e-book](http://helion.pl/add111546~rubyw2_ebook)

2. B. Frain, _Responsive Web Design. Projektowanie elastycznych witryn w HTML5 i CSS3_, [Zobacz opis](http://helion.pl/view/111546/resweb) lub [Kup e-book](http://helion.pl/add111546~resweb_ebook)

3. K. Beck, _TDD. Sztuda tworzenia_, [Zobacz opis](http://helion.pl/view/111546/tddszv) lub [Kup teraz](http://helion.pl/add111546~tddszv), [Kup e-book](http://helion.pl/add111546~tddszv_ebook)

4. B. Dayley, _Node.js, MongoDB, AngularJS. Kompendium wiedzy_, [Zobacz opis](http://helion.pl/view/111546/tddszv) lub [Kup teraz](http://helion.pl/add111546~tddszv), [Kup e-book](http://helion.pl/add111546~tddszv_ebook)

### Qauntum Computing

1. A. Jacquier, O. Kondratyev, _Quantum Machine Learning and Optimisation in Finance. On the Road to Quantum Advantage_.

## Strony WWW

### Software 

1. [Github](https://github.com/)
2. [Git-instrukcja](https://git-scm.com/book/pl/v2)
3. [www.python.org](http://www.python.org/downloads/)
4. [PyPI python libraries](https://pypi.python.org/pypi)
5. [Anaconda](http://continuum.io/downloads)
6. [Docker](https://docs.docker.com/get-docker/)

### Pakiety python dla analiz danych

1. [NumPy](http://www.numpy.org)
2. [SciPy](http://www.scipy.org)
3. [Pandas](http://pandas.pydata.org)
4. [Scikit-learn](http://scikit-learn.org/stable)
5. [Jupyter](http://jupyter.org)
6. [Matplotlib](http://matplotlib.org)
7. [Beautiful Soup](http://wwwcrummy.com/software/BeautifulSoup)
8. [Theano](http://deeplearning.net/software/theano)
9. [Keras](http://keras.io)
10. [TensorFlow](https://www.tensorflow.org)
11. [Virtual ENV](https://docs.python.org/3/tutorial/venv.html)

### Edytory tekstu

1. [Notepad++](https://notepad-plus-plus.org/download)
2. [Sublime Text](https://www.sublimetext.com)
3. [Visual Studio Code](https://code.visualstudio.com)

### Markdown

1. [MD](http://daringfireball.net/projects/markdown/)

### Jupyter notebook

1. [Galeria ciekawych notatników](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks#accessing-an-ibm-quantum-computer-via-notebooks)
2. [Intro](https://www.youtube.com/watch?v=HW29067qVWk)
3. [Kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels)
4. [Bringing the best out of jupyter for data science](https://towardsdatascience.com/bringing-the-best-out-of-jupyter-notebooks-for-data-science-f0871519ca29)
5. [Jupyter extensions](https://towardsdatascience.com/jupyter-notebook-extensions-517fa69d2231)
6. [I don't like notebooks](https://www.youtube.com/watch?v=7jiPeIFXb6U)
7. [Jupyter lab](https://www.youtube.com/watch?v=NSiPeoDpwuI)
8. [Speed up jupyter notebook](https://towardsdatascience.com/speed-up-jupyter-notebooks-20716cbe2025)

### Przetwarzanie danych

1. [data cookbook](https://www.datafix.com.au/cookbook/index.html)

### Zbiory danych

- [Internet Archive](https://oreil.ly/tIjl9)
- [Reddit](http://reddit.com/r/datasets)
- [KDnuggets](https://www.kdnuggets.com)
- [Kaggle](https://www.kaggle.com/datasets)
- [List of datasets for machine learning research](https://en.wikipedia.org/wiki/List_of_datasets_for_machine_learning_research)
- [UCI Machine Learning Repo](https://oreil.ly/BXLA5)
- [Public API](https://github.com/toddmotto/public-apis)
- [Google Datatset Search](https://oreil.ly/Gpv8S)

### Python

1. [Chris Albon](https://chrisalbon.com/) Technical Notes on Using **Data Science & AI** 
2. [40+ Python Statistics For Data Science Resources](https://www.datacamp.com/community/tutorials/python-statistics-data-science)
3. [Practical Business Python](http://pbpython.com/)

### kursy ML

1. [Kurs Machine Learning - Andrew Ng, Stanford](https://www.youtube.com/watch?v=PPLop4L2eGk&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN)
2. [Kurs Machine Learning - Andrew Ng, Stanford](https://www.coursera.org/learn/machine-learning)
3. [Python programming for data science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html)