---
title: Sylabus
---

> Nazwa przedmiotu: Analiza danych w czasie rzeczywistym
> 
> Jednostka: Szkoa G贸wna Handlowa w Warszawie
> 
> Kod przedmiotu: 222890-D, 222890-S
>
> Punkty ECTS: 3
>
> Jzyk prowadzenia: polski
>
> Poziom przedmiotu: rednio-zaawansowany


**Prowadzcy:** [Sebastian Zajc](https://sebastianzajac.pl), 
  [sebastian.zajac@sgh.waw.pl](mailto:sebastian.zajac@sgh.waw.pl)


**Website:**
  [https://sebkaz-teaching.github.io/RTA_2025/](https://sebkaz-teaching.github.io/RTA_2025/)



## Cel Przedmiotu

Wsp贸czesny biznes opiera si na podejmowaniu decyzji opartych na danych. 
Coraz wiksza ilo informacji, rosnce wymagania rynku oraz potrzeba natychmiastowej reakcji sprawiaj, 偶e analiza danych w czasie rzeczywistym staje si kluczowym elementem nowoczesnych proces贸w biznesowych.

Na zajciach studenci zapoznaj si z metodami i technologiami umo偶liwiajcymi przetwarzanie danych w czasie rzeczywistym. 
Szczeg贸ln uwag powicimy zastosowaniu uczenia maszynowego (machine learning), sztucznej inteligencji (artificial intelligence) oraz gbokich sieci neuronowych (deep learning) w analizie danych. 
Zrozumienie tych metod pozwala nie tylko lepiej interpretowa zjawiska biznesowe, ale tak偶e podejmowa szybkie i trafne decyzje.

W ramach kursu om贸wimy zar贸wno dane ustrukturyzowane, jak i nieustrukturyzowane (obrazy, d藕wik, strumieniowanie wideo). 
Studenci poznaj architektury przetwarzania danych, takie jak lambda i kappa, wykorzystywane w systemach data lake, a tak偶e wyzwania zwizane z modelowaniem danych w czasie rzeczywistym na du偶 skal.

Kurs obejmuje cz teoretyczn oraz praktyczne laboratoria, podczas kt贸rych studenci bd pracowa z rzeczywistymi danymi w rodowiskach takich jak: JupyterLab, PyTorch, Apache Spark, Apache Kafka. 
Dziki temu studenci nie tylko zdobd wiedz na temat metod analitycznych, ale tak偶e naucz si korzysta z najnowszych technologii informatycznych stosowanych w analizie danych w czasie rzeczywistym.

## Program przedmiotu

1. Modelowanie, uczenie i predykcja w trybie wsadowym (offline learning) i przyrostowym (online learning). Problemy przyrostowego uczenia maszynowego.
2. Modele przetwarzania danych w Big Data. Od plikow paskich do Data Lake. Mity i fakty przetwarzania danych w czasie rzeczywistym. (Wykad)
3. Systemy NRT (near real-time systems), pozyskiwanie danych, streaming, analityka.
4. Algorytmy estymacji parametrow modelu w trybie przyrostowym. Stochastic Gradient Descent.
5. Architektura Lambda i Kappa. Zaprojektowanie architektury IT dla przetwarzania danych w czasie rzeczywistym.
6. Przygotowanie mikroserwisu z modelem ML do zastosowania produkcyjnego.
7. Strukturyzowane i niestrukturyzowane dane. Relacyjne bazy danych i bazy NoSQL
8. Agregacje i raportowanie w bazach NoSQL (na przykadzie bazy Cassandra).
9. Podstawy obiektowego programowania w Pythonie w analizie regresji liniowej, logistycznej oraz sieci neuronowych z wykorzystaniem biblioteki sklearn, TensorFLow i Keras
10. Architektura IT przetwarzania Big Data. Przygotowanie wirtualnego srodowiska dla Sparka. Pierwszy program w PySpark. Wykorzystanie przygotowanego srodowiska do analizy danych z serwisu Twitter.
11. Analiza 1 Detekcja wyudzen w zgoszeniach szkod samochodowych w czasie rzeczywistym z wykorzystaniem przygotowanego, darmowego srodowiska. Cz 1.
12. Analiza 1 Detekcja wyudzen w zgoszeniach szkod samochodowych w czasie rzeczywistym z wykorzystaniem przygotowanego, darmowego srodowiska. Cz 2.
13. Przygotowanie srodowiska Microsoft Azure. Detekcja anomalii i wartosci odstaja台cych w logowanych zdarzeniach sieci Ethernet cz 1.
14. Analiza 2 Detekcja anomalii i wartosci odstaja台cych w logowanych zdarzeniach sieci Ethernet cz 2. Inne narze台dzia IT do szybkiej analizy logow.
15. Narze台dzia SAS do strumieniowego przetwarzania danych

## Efekty ksztacenia

1. Wiedza:

- Zna historie台 i filozofie台 modeli przetwarzania danych

Powia台zania: (Analiza danych - Big Data)K2A_W01, (Analiza danych - Big Data)K2A_W03, (OGL)O2_W01, (OGL) O2_W02, (OGL)O2_W04, (OGL)O2_W07

Metody weryfikacji: kolokwium pisemne (pytania otwarte, zadania)

Metody dokumentacji: wykaz pytan z kolokwium

- Zna typy danych ustrukturyzowanych jak i nieustrukturyzowanych

Powia台zania: (Analiza danych - Big Data)K2A_W02, (Analiza danych - Big Data)K2A_W04, (OGL)O2_W04, (OGL) O2_W07

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Zna mozliwosci i obszary zastosowania procesowania danych w czasie rzeczywistym

Powia台zania: (Analiza danych - Big Data)K2A_W01, (Analiza danych - Big Data)K2A_W02, (OGL)O2_W01, (OGL) O2_W04, (OGL)O2_W08

Metody weryfikacji: egzamin pisemny (pytania otwarte, zadania)

Metody dokumentacji: wykaz pytan egzaminacyjnych

- Zna teoretyczne aspekty struktury lambda i kappa

Powia台zania: (Analiza danych - Big Data)K2A_W03, (Analiza danych - Big Data)K2A_W05, (OGL)O2_W04, (OGL) O2_W06, (OGL)O2_W08

Metody weryfikacji: kolokwium pisemne (pytania otwarte, zadania)

Metody dokumentacji: wykaz pytan z kolokwium

- Umie wybrac strukture台 IT dla danego problemu biznesowego

Powia台zania: (Analiza danych - Big Data)K2A_W02, (Analiza danych - Big Data)K2A_W03, (OGL)O2_W01, (OGL) O2_W04, (OGL)O2_W06, (OGL)O2_W08

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Rozumie potrzeby biznesowe podejmowania decyzji w bardzo krotkim czasie

Powia台zania: (Analiza danych - Big Data)K2A_W01, (Analiza danych - Big Data)K2A_W05, (OGL)O2_W01, (OGL) O2_W04, (OGL)O2_W06, (OGL)O2_W08

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

2. Umiejtnoci:

- Rozroznia typy danych strukturyzowanych jak i niestrukturyzowanych

Powia台zania: K2A_U02, K2A_U07, K2A_U10, O2_U02

Metody weryfikacji: test

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Umie przygotowac, przetwarzac oraz zachowywac dane generowane w czasie rzeczywistym

Powia台zania:  K2A_U03, K2A_U05, K2A_U09, O2_U02, O2_U04

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Rozumie ograniczenia wynikaja台ce z czasu przetwarzania przez urza台dzenia oraz systemy informatyczne

Powia台zania:  K2A_U01, K2A_U07, K2A_U11, O2_U02

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Umie zastosowac i skonstruowac system do przetwarzania w czasie rzeczywistym

Powia台zania:  K2A_U05, K2A_U10, O2_U05, O2_U06, O2_U07

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Umie przygotowac raportowanie dla systemu przetwarzania w czasie rzeczywistym

Powia台zania: K2A_U02, K2A_U08, K2A_U10, O2_U06, O2_U07

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)

3. Kompetencje:

- Formuuje problem analityczny wraz z jego informatycznym rozwia台zaniem

Powia台zania: K2A_K01, K2A_K03, O2_K02,  O2_K06, O2_K07

Metody weryfikacji: projekt, prezentacja

Metody dokumentacji: prace pisemne studenta (w trakcie semestru, zaliczeniowe, egzaminacyjne)

- Utrwala umieje台tnosc samodzielnego uzupeniania wiedzy teoretycznej jak i praktycznej w zakresie programowania,
modelowania, nowych technologii informatycznych z wykorzystaniem analizy w czasie rzeczywistym. 

Powia台zania: K2A_K02, K2A_K04, (OGL)O2_K01, (OGL) O2_K02, (OGL)O2_K05, (OGL)O2_K06

Metody weryfikacji: projekt

Metody dokumentacji: prace pisemne studenta ( w trakcie semestru, zaliczeniowe, egzaminacyjne)


## Realizacja przedmiotu

- egzamin testowy 20%
- Zadania 40% 
- Projekt 40%


## Literatura


1锔 Zajc S. (red.), Modelowanie dla biznesu, Analityka w czasie rzeczywistym - narzdzia informatyczne i biznesowe, SGH, Warszawa 2022.

2锔 Frtczak E. (red.), Modelowanie dla biznesu: Regresja logistyczna, Regresja Poissona, Survival Data Mining, CRM, Credit Scoring, SGH, Warszawa 2019.

3锔 Bellemare A., Mikrousugi oparte na zdarzeniach. Wykorzystanie danych w organizacji na du偶 skal, O'Reilly 2021.

4锔 Shapira G., Palino T., Sivaram R., Petty K., Kafka: The Definitive Guide. Real-time data and stream processing at scale, O'Reilly 2022.

5锔 Lakshmanan V., Robinson S., Munn M., Wzorce projektowe uczenia maszynowego. Rozwizania typowych problem贸w dotyczcych przygotowania danych, konstruowania modeli i MLOps, O'Reilly 2021.

6锔 Gift N., Deza A., Practical MLOps: Operationalizing Machine Learning Models, O'Reilly 2022.

7锔 Tiark Rompf, Streaming Systems: The What, Where, When, and How of Large-Scale Data Processing, O'Reilly 2018.

8锔 Sebasti谩n Ram铆rez, FastAPI: Modern Web APIs with Python, Manning (w przygotowaniu, aktualnie dostpna online).

9锔 Trevor Hastie, Robert Tibshirani, Jerome Friedman, The Elements of Statistical Learning: Data Mining, Inference, and Prediction, Springer 2017.

 Anirudh Koul, Siddha Ganju, Meher Kasam, Practical Deep Learning for Cloud, Mobile & Edge, O'Reilly 2019.

